extension_dir = "C:\Users\user\AppData\Local\Microsoft\WinGet\Packages\PHP.PHP.8.3_Microsoft.Winget.Source_8wekyb3d8bbwe\ext"
extension = pdo_sqlite
extension = sqlite3
extension = mbstring
extension = curl
extension = openssl
extension = fileinfo
extension = gd
extension = zip

upload_max_filesize = 10M
post_max_size = 10M
memory_limit = 128M
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
